
server:
  port: 6996
  servlet:
    context-path: /mingyue



spring:
  servlet:
    multipart:
      max-file-size: 9999MB
      max-request-size: 9999MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mingyue?serverTimezone=GMT%2B8
    username: root
    password: as521968
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis: #springboot2
    host: 192.168.31.193
    port: 6379

    #  data:  springboot3
    #    redis:
    #      host: localhost
    #      port: 6379
    #      password: as521968
    #  config:
    #    import: classpath:security/applicationContext-shiro.xml
  rabbitmq:
    host: 192.168.31.193
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息 处理完成才能获取下一条 能者多劳模式 默认为预取机制
        acknowledge-mode: manual # 设置消费端手动ack确认
        retry:
          enabled: true # 是否支持重试
      direct:
        acknowledge-mode: manual
    publisher-confirm-type: correlated # 确认消息已发送到交换机(Exchange)
    publisher-returns: true #  确认消息已发送到队列(Queue) 消息在未被队列接收时返回


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.*.*.dao
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helper-dialect: mysql #指定数据库
  reasonable: true #开启合理化分页
  support-methods-arguments: true #支持方法参数未Page类型
  params: count=countSql #指定

logging:
  config: classpath:log4j.properties


file:
  upload:
    path: /home/mingyue/upload
#   path: src/main/resources/upload

config:


jedis:
  pool:
    host: 192.168.31.193
    port: 6379
    password:
    timeout: 7200
    maxTotall: 20
    maxIdle: 50
    minIdle: 20
    maxWaitMillis: 10000
    testOnBorrow: true
    testOnRerurn: true,
    timeBetweenEvictionRunsMillis: 30000
    testWhileIdle: true
    numTestPerEvictionRun: 50